//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeDomain) DeepCopyInto(out *BridgeDomain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeDomain.
func (in *BridgeDomain) DeepCopy() *BridgeDomain {
	if in == nil {
		return nil
	}
	out := new(BridgeDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BridgeDomain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeDomainList) DeepCopyInto(out *BridgeDomainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BridgeDomain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeDomainList.
func (in *BridgeDomainList) DeepCopy() *BridgeDomainList {
	if in == nil {
		return nil
	}
	out := new(BridgeDomainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BridgeDomainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeDomainObservation) DeepCopyInto(out *BridgeDomainObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeDomainObservation.
func (in *BridgeDomainObservation) DeepCopy() *BridgeDomainObservation {
	if in == nil {
		return nil
	}
	out := new(BridgeDomainObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeDomainParameters) DeepCopyInto(out *BridgeDomainParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.ArpFlood != nil {
		in, out := &in.ArpFlood, &out.ArpFlood
		*out = new(string)
		**out = **in
	}
	if in.BridgeDomainType != nil {
		in, out := &in.BridgeDomainType, &out.BridgeDomainType
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EpClear != nil {
		in, out := &in.EpClear, &out.EpClear
		*out = new(string)
		**out = **in
	}
	if in.EpMoveDetectMode != nil {
		in, out := &in.EpMoveDetectMode, &out.EpMoveDetectMode
		*out = new(string)
		**out = **in
	}
	if in.HostBasedRouting != nil {
		in, out := &in.HostBasedRouting, &out.HostBasedRouting
		*out = new(string)
		**out = **in
	}
	if in.IPLearning != nil {
		in, out := &in.IPLearning, &out.IPLearning
		*out = new(string)
		**out = **in
	}
	if in.IPv6McastAllow != nil {
		in, out := &in.IPv6McastAllow, &out.IPv6McastAllow
		*out = new(string)
		**out = **in
	}
	if in.IntersiteBumTrafficAllow != nil {
		in, out := &in.IntersiteBumTrafficAllow, &out.IntersiteBumTrafficAllow
		*out = new(string)
		**out = **in
	}
	if in.IntersiteL2Stretch != nil {
		in, out := &in.IntersiteL2Stretch, &out.IntersiteL2Stretch
		*out = new(string)
		**out = **in
	}
	if in.LimitIPLearnToSubnets != nil {
		in, out := &in.LimitIPLearnToSubnets, &out.LimitIPLearnToSubnets
		*out = new(string)
		**out = **in
	}
	if in.LlAddr != nil {
		in, out := &in.LlAddr, &out.LlAddr
		*out = new(string)
		**out = **in
	}
	if in.Mac != nil {
		in, out := &in.Mac, &out.Mac
		*out = new(string)
		**out = **in
	}
	if in.McastAllow != nil {
		in, out := &in.McastAllow, &out.McastAllow
		*out = new(string)
		**out = **in
	}
	if in.MultiDstPktAct != nil {
		in, out := &in.MultiDstPktAct, &out.MultiDstPktAct
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
	if in.OptimizeWanBandwidth != nil {
		in, out := &in.OptimizeWanBandwidth, &out.OptimizeWanBandwidth
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsAbdPolMonPol != nil {
		in, out := &in.RelationFvRsAbdPolMonPol, &out.RelationFvRsAbdPolMonPol
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsBdFloodTo != nil {
		in, out := &in.RelationFvRsBdFloodTo, &out.RelationFvRsBdFloodTo
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsBdToEpRet != nil {
		in, out := &in.RelationFvRsBdToEpRet, &out.RelationFvRsBdToEpRet
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsBdToFhs != nil {
		in, out := &in.RelationFvRsBdToFhs, &out.RelationFvRsBdToFhs
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsBdToNdP != nil {
		in, out := &in.RelationFvRsBdToNdP, &out.RelationFvRsBdToNdP
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsBdToNetflowMonitorPol != nil {
		in, out := &in.RelationFvRsBdToNetflowMonitorPol, &out.RelationFvRsBdToNetflowMonitorPol
		*out = make([]RelationFvRsBdToNetflowMonitorPolParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RelationFvRsBdToOut != nil {
		in, out := &in.RelationFvRsBdToOut, &out.RelationFvRsBdToOut
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsBdToProfile != nil {
		in, out := &in.RelationFvRsBdToProfile, &out.RelationFvRsBdToProfile
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsBdToRelayP != nil {
		in, out := &in.RelationFvRsBdToRelayP, &out.RelationFvRsBdToRelayP
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsCtx != nil {
		in, out := &in.RelationFvRsCtx, &out.RelationFvRsCtx
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsIgmpsn != nil {
		in, out := &in.RelationFvRsIgmpsn, &out.RelationFvRsIgmpsn
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsMldsn != nil {
		in, out := &in.RelationFvRsMldsn, &out.RelationFvRsMldsn
		*out = new(string)
		**out = **in
	}
	if in.TenantDn != nil {
		in, out := &in.TenantDn, &out.TenantDn
		*out = new(string)
		**out = **in
	}
	if in.TenantDnRef != nil {
		in, out := &in.TenantDnRef, &out.TenantDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.TenantDnSelector != nil {
		in, out := &in.TenantDnSelector, &out.TenantDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.UnicastRoute != nil {
		in, out := &in.UnicastRoute, &out.UnicastRoute
		*out = new(string)
		**out = **in
	}
	if in.UnkMacUcastAct != nil {
		in, out := &in.UnkMacUcastAct, &out.UnkMacUcastAct
		*out = new(string)
		**out = **in
	}
	if in.UnkMcastAct != nil {
		in, out := &in.UnkMcastAct, &out.UnkMcastAct
		*out = new(string)
		**out = **in
	}
	if in.V6UnkMcastAct != nil {
		in, out := &in.V6UnkMcastAct, &out.V6UnkMcastAct
		*out = new(string)
		**out = **in
	}
	if in.Vmac != nil {
		in, out := &in.Vmac, &out.Vmac
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeDomainParameters.
func (in *BridgeDomainParameters) DeepCopy() *BridgeDomainParameters {
	if in == nil {
		return nil
	}
	out := new(BridgeDomainParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeDomainSpec) DeepCopyInto(out *BridgeDomainSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeDomainSpec.
func (in *BridgeDomainSpec) DeepCopy() *BridgeDomainSpec {
	if in == nil {
		return nil
	}
	out := new(BridgeDomainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeDomainStatus) DeepCopyInto(out *BridgeDomainStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeDomainStatus.
func (in *BridgeDomainStatus) DeepCopy() *BridgeDomainStatus {
	if in == nil {
		return nil
	}
	out := new(BridgeDomainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3ExternalNetworkInstanceProfile) DeepCopyInto(out *L3ExternalNetworkInstanceProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3ExternalNetworkInstanceProfile.
func (in *L3ExternalNetworkInstanceProfile) DeepCopy() *L3ExternalNetworkInstanceProfile {
	if in == nil {
		return nil
	}
	out := new(L3ExternalNetworkInstanceProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L3ExternalNetworkInstanceProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3ExternalNetworkInstanceProfileList) DeepCopyInto(out *L3ExternalNetworkInstanceProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]L3ExternalNetworkInstanceProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3ExternalNetworkInstanceProfileList.
func (in *L3ExternalNetworkInstanceProfileList) DeepCopy() *L3ExternalNetworkInstanceProfileList {
	if in == nil {
		return nil
	}
	out := new(L3ExternalNetworkInstanceProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L3ExternalNetworkInstanceProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3ExternalNetworkInstanceProfileObservation) DeepCopyInto(out *L3ExternalNetworkInstanceProfileObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3ExternalNetworkInstanceProfileObservation.
func (in *L3ExternalNetworkInstanceProfileObservation) DeepCopy() *L3ExternalNetworkInstanceProfileObservation {
	if in == nil {
		return nil
	}
	out := new(L3ExternalNetworkInstanceProfileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3ExternalNetworkInstanceProfileParameters) DeepCopyInto(out *L3ExternalNetworkInstanceProfileParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ExceptionTag != nil {
		in, out := &in.ExceptionTag, &out.ExceptionTag
		*out = new(string)
		**out = **in
	}
	if in.FloodOnEncap != nil {
		in, out := &in.FloodOnEncap, &out.FloodOnEncap
		*out = new(string)
		**out = **in
	}
	if in.L3OutsideDn != nil {
		in, out := &in.L3OutsideDn, &out.L3OutsideDn
		*out = new(string)
		**out = **in
	}
	if in.L3OutsideDnRef != nil {
		in, out := &in.L3OutsideDnRef, &out.L3OutsideDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.L3OutsideDnSelector != nil {
		in, out := &in.L3OutsideDnSelector, &out.L3OutsideDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.MatchT != nil {
		in, out := &in.MatchT, &out.MatchT
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
	if in.PrefGrMemb != nil {
		in, out := &in.PrefGrMemb, &out.PrefGrMemb
		*out = new(string)
		**out = **in
	}
	if in.Prio != nil {
		in, out := &in.Prio, &out.Prio
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsCons != nil {
		in, out := &in.RelationFvRsCons, &out.RelationFvRsCons
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsConsIf != nil {
		in, out := &in.RelationFvRsConsIf, &out.RelationFvRsConsIf
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsCustQosPol != nil {
		in, out := &in.RelationFvRsCustQosPol, &out.RelationFvRsCustQosPol
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsIntraEpg != nil {
		in, out := &in.RelationFvRsIntraEpg, &out.RelationFvRsIntraEpg
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsProtBy != nil {
		in, out := &in.RelationFvRsProtBy, &out.RelationFvRsProtBy
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsProv != nil {
		in, out := &in.RelationFvRsProv, &out.RelationFvRsProv
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsSecInherited != nil {
		in, out := &in.RelationFvRsSecInherited, &out.RelationFvRsSecInherited
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationL3ExtRsInstPToNATMappingEpg != nil {
		in, out := &in.RelationL3ExtRsInstPToNATMappingEpg, &out.RelationL3ExtRsInstPToNATMappingEpg
		*out = new(string)
		**out = **in
	}
	if in.RelationL3ExtRsInstPToProfile != nil {
		in, out := &in.RelationL3ExtRsInstPToProfile, &out.RelationL3ExtRsInstPToProfile
		*out = make([]RelationL3ExtRsInstPToProfileParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RelationL3ExtRsL3InstPToDomP != nil {
		in, out := &in.RelationL3ExtRsL3InstPToDomP, &out.RelationL3ExtRsL3InstPToDomP
		*out = new(string)
		**out = **in
	}
	if in.TargetDscp != nil {
		in, out := &in.TargetDscp, &out.TargetDscp
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3ExternalNetworkInstanceProfileParameters.
func (in *L3ExternalNetworkInstanceProfileParameters) DeepCopy() *L3ExternalNetworkInstanceProfileParameters {
	if in == nil {
		return nil
	}
	out := new(L3ExternalNetworkInstanceProfileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3ExternalNetworkInstanceProfileSpec) DeepCopyInto(out *L3ExternalNetworkInstanceProfileSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3ExternalNetworkInstanceProfileSpec.
func (in *L3ExternalNetworkInstanceProfileSpec) DeepCopy() *L3ExternalNetworkInstanceProfileSpec {
	if in == nil {
		return nil
	}
	out := new(L3ExternalNetworkInstanceProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3ExternalNetworkInstanceProfileStatus) DeepCopyInto(out *L3ExternalNetworkInstanceProfileStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3ExternalNetworkInstanceProfileStatus.
func (in *L3ExternalNetworkInstanceProfileStatus) DeepCopy() *L3ExternalNetworkInstanceProfileStatus {
	if in == nil {
		return nil
	}
	out := new(L3ExternalNetworkInstanceProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3ExternalSubnet) DeepCopyInto(out *L3ExternalSubnet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3ExternalSubnet.
func (in *L3ExternalSubnet) DeepCopy() *L3ExternalSubnet {
	if in == nil {
		return nil
	}
	out := new(L3ExternalSubnet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L3ExternalSubnet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3ExternalSubnetList) DeepCopyInto(out *L3ExternalSubnetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]L3ExternalSubnet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3ExternalSubnetList.
func (in *L3ExternalSubnetList) DeepCopy() *L3ExternalSubnetList {
	if in == nil {
		return nil
	}
	out := new(L3ExternalSubnetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L3ExternalSubnetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3ExternalSubnetObservation) DeepCopyInto(out *L3ExternalSubnetObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3ExternalSubnetObservation.
func (in *L3ExternalSubnetObservation) DeepCopy() *L3ExternalSubnetObservation {
	if in == nil {
		return nil
	}
	out := new(L3ExternalSubnetObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3ExternalSubnetParameters) DeepCopyInto(out *L3ExternalSubnetParameters) {
	*out = *in
	if in.Aggregate != nil {
		in, out := &in.Aggregate, &out.Aggregate
		*out = new(string)
		**out = **in
	}
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ExternalNetworkInstanceProfileDn != nil {
		in, out := &in.ExternalNetworkInstanceProfileDn, &out.ExternalNetworkInstanceProfileDn
		*out = new(string)
		**out = **in
	}
	if in.ExternalNetworkInstanceProfileDnRef != nil {
		in, out := &in.ExternalNetworkInstanceProfileDnRef, &out.ExternalNetworkInstanceProfileDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.ExternalNetworkInstanceProfileDnSelector != nil {
		in, out := &in.ExternalNetworkInstanceProfileDnSelector, &out.ExternalNetworkInstanceProfileDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
	if in.RelationL3ExtRsSubnetToProfile != nil {
		in, out := &in.RelationL3ExtRsSubnetToProfile, &out.RelationL3ExtRsSubnetToProfile
		*out = make([]RelationL3ExtRsSubnetToProfileParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RelationL3ExtRsSubnetToRtSumm != nil {
		in, out := &in.RelationL3ExtRsSubnetToRtSumm, &out.RelationL3ExtRsSubnetToRtSumm
		*out = new(string)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3ExternalSubnetParameters.
func (in *L3ExternalSubnetParameters) DeepCopy() *L3ExternalSubnetParameters {
	if in == nil {
		return nil
	}
	out := new(L3ExternalSubnetParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3ExternalSubnetSpec) DeepCopyInto(out *L3ExternalSubnetSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3ExternalSubnetSpec.
func (in *L3ExternalSubnetSpec) DeepCopy() *L3ExternalSubnetSpec {
	if in == nil {
		return nil
	}
	out := new(L3ExternalSubnetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3ExternalSubnetStatus) DeepCopyInto(out *L3ExternalSubnetStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3ExternalSubnetStatus.
func (in *L3ExternalSubnetStatus) DeepCopy() *L3ExternalSubnetStatus {
	if in == nil {
		return nil
	}
	out := new(L3ExternalSubnetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3LogicalInterfaceProfile) DeepCopyInto(out *L3LogicalInterfaceProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3LogicalInterfaceProfile.
func (in *L3LogicalInterfaceProfile) DeepCopy() *L3LogicalInterfaceProfile {
	if in == nil {
		return nil
	}
	out := new(L3LogicalInterfaceProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L3LogicalInterfaceProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3LogicalInterfaceProfileList) DeepCopyInto(out *L3LogicalInterfaceProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]L3LogicalInterfaceProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3LogicalInterfaceProfileList.
func (in *L3LogicalInterfaceProfileList) DeepCopy() *L3LogicalInterfaceProfileList {
	if in == nil {
		return nil
	}
	out := new(L3LogicalInterfaceProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L3LogicalInterfaceProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3LogicalInterfaceProfileObservation) DeepCopyInto(out *L3LogicalInterfaceProfileObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3LogicalInterfaceProfileObservation.
func (in *L3LogicalInterfaceProfileObservation) DeepCopy() *L3LogicalInterfaceProfileObservation {
	if in == nil {
		return nil
	}
	out := new(L3LogicalInterfaceProfileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3LogicalInterfaceProfileParameters) DeepCopyInto(out *L3LogicalInterfaceProfileParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.LogicalNodeProfileDn != nil {
		in, out := &in.LogicalNodeProfileDn, &out.LogicalNodeProfileDn
		*out = new(string)
		**out = **in
	}
	if in.LogicalNodeProfileDnRef != nil {
		in, out := &in.LogicalNodeProfileDnRef, &out.LogicalNodeProfileDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.LogicalNodeProfileDnSelector != nil {
		in, out := &in.LogicalNodeProfileDnSelector, &out.LogicalNodeProfileDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
	if in.Prio != nil {
		in, out := &in.Prio, &out.Prio
		*out = new(string)
		**out = **in
	}
	if in.RelationL3ExtRsArpIfPol != nil {
		in, out := &in.RelationL3ExtRsArpIfPol, &out.RelationL3ExtRsArpIfPol
		*out = new(string)
		**out = **in
	}
	if in.RelationL3ExtRsEgressQosDppPol != nil {
		in, out := &in.RelationL3ExtRsEgressQosDppPol, &out.RelationL3ExtRsEgressQosDppPol
		*out = new(string)
		**out = **in
	}
	if in.RelationL3ExtRsIngressQosDppPol != nil {
		in, out := &in.RelationL3ExtRsIngressQosDppPol, &out.RelationL3ExtRsIngressQosDppPol
		*out = new(string)
		**out = **in
	}
	if in.RelationL3ExtRsLIfPCustQosPol != nil {
		in, out := &in.RelationL3ExtRsLIfPCustQosPol, &out.RelationL3ExtRsLIfPCustQosPol
		*out = new(string)
		**out = **in
	}
	if in.RelationL3ExtRsLIfPToNetflowMonitorPol != nil {
		in, out := &in.RelationL3ExtRsLIfPToNetflowMonitorPol, &out.RelationL3ExtRsLIfPToNetflowMonitorPol
		*out = make([]RelationL3ExtRsLIfPToNetflowMonitorPolParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RelationL3ExtRsNdIfPol != nil {
		in, out := &in.RelationL3ExtRsNdIfPol, &out.RelationL3ExtRsNdIfPol
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3LogicalInterfaceProfileParameters.
func (in *L3LogicalInterfaceProfileParameters) DeepCopy() *L3LogicalInterfaceProfileParameters {
	if in == nil {
		return nil
	}
	out := new(L3LogicalInterfaceProfileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3LogicalInterfaceProfileSpec) DeepCopyInto(out *L3LogicalInterfaceProfileSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3LogicalInterfaceProfileSpec.
func (in *L3LogicalInterfaceProfileSpec) DeepCopy() *L3LogicalInterfaceProfileSpec {
	if in == nil {
		return nil
	}
	out := new(L3LogicalInterfaceProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3LogicalInterfaceProfileStatus) DeepCopyInto(out *L3LogicalInterfaceProfileStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3LogicalInterfaceProfileStatus.
func (in *L3LogicalInterfaceProfileStatus) DeepCopy() *L3LogicalInterfaceProfileStatus {
	if in == nil {
		return nil
	}
	out := new(L3LogicalInterfaceProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3LogicalNodeProfile) DeepCopyInto(out *L3LogicalNodeProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3LogicalNodeProfile.
func (in *L3LogicalNodeProfile) DeepCopy() *L3LogicalNodeProfile {
	if in == nil {
		return nil
	}
	out := new(L3LogicalNodeProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L3LogicalNodeProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3LogicalNodeProfileList) DeepCopyInto(out *L3LogicalNodeProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]L3LogicalNodeProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3LogicalNodeProfileList.
func (in *L3LogicalNodeProfileList) DeepCopy() *L3LogicalNodeProfileList {
	if in == nil {
		return nil
	}
	out := new(L3LogicalNodeProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L3LogicalNodeProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3LogicalNodeProfileObservation) DeepCopyInto(out *L3LogicalNodeProfileObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3LogicalNodeProfileObservation.
func (in *L3LogicalNodeProfileObservation) DeepCopy() *L3LogicalNodeProfileObservation {
	if in == nil {
		return nil
	}
	out := new(L3LogicalNodeProfileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3LogicalNodeProfileParameters) DeepCopyInto(out *L3LogicalNodeProfileParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.ConfigIssues != nil {
		in, out := &in.ConfigIssues, &out.ConfigIssues
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.L3OutsideDn != nil {
		in, out := &in.L3OutsideDn, &out.L3OutsideDn
		*out = new(string)
		**out = **in
	}
	if in.L3OutsideDnRef != nil {
		in, out := &in.L3OutsideDnRef, &out.L3OutsideDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.L3OutsideDnSelector != nil {
		in, out := &in.L3OutsideDnSelector, &out.L3OutsideDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
	if in.TargetDscp != nil {
		in, out := &in.TargetDscp, &out.TargetDscp
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3LogicalNodeProfileParameters.
func (in *L3LogicalNodeProfileParameters) DeepCopy() *L3LogicalNodeProfileParameters {
	if in == nil {
		return nil
	}
	out := new(L3LogicalNodeProfileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3LogicalNodeProfileSpec) DeepCopyInto(out *L3LogicalNodeProfileSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3LogicalNodeProfileSpec.
func (in *L3LogicalNodeProfileSpec) DeepCopy() *L3LogicalNodeProfileSpec {
	if in == nil {
		return nil
	}
	out := new(L3LogicalNodeProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3LogicalNodeProfileStatus) DeepCopyInto(out *L3LogicalNodeProfileStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3LogicalNodeProfileStatus.
func (in *L3LogicalNodeProfileStatus) DeepCopy() *L3LogicalNodeProfileStatus {
	if in == nil {
		return nil
	}
	out := new(L3LogicalNodeProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3Outside) DeepCopyInto(out *L3Outside) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3Outside.
func (in *L3Outside) DeepCopy() *L3Outside {
	if in == nil {
		return nil
	}
	out := new(L3Outside)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L3Outside) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3OutsideList) DeepCopyInto(out *L3OutsideList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]L3Outside, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3OutsideList.
func (in *L3OutsideList) DeepCopy() *L3OutsideList {
	if in == nil {
		return nil
	}
	out := new(L3OutsideList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L3OutsideList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3OutsideObservation) DeepCopyInto(out *L3OutsideObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3OutsideObservation.
func (in *L3OutsideObservation) DeepCopy() *L3OutsideObservation {
	if in == nil {
		return nil
	}
	out := new(L3OutsideObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3OutsideParameters) DeepCopyInto(out *L3OutsideParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EnforceRtctrl != nil {
		in, out := &in.EnforceRtctrl, &out.EnforceRtctrl
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
	if in.RelationL3ExtRsDampeningPol != nil {
		in, out := &in.RelationL3ExtRsDampeningPol, &out.RelationL3ExtRsDampeningPol
		*out = make([]RelationL3ExtRsDampeningPolParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RelationL3ExtRsEctx != nil {
		in, out := &in.RelationL3ExtRsEctx, &out.RelationL3ExtRsEctx
		*out = new(string)
		**out = **in
	}
	if in.RelationL3ExtRsInterleakPol != nil {
		in, out := &in.RelationL3ExtRsInterleakPol, &out.RelationL3ExtRsInterleakPol
		*out = new(string)
		**out = **in
	}
	if in.RelationL3ExtRsL3DomAtt != nil {
		in, out := &in.RelationL3ExtRsL3DomAtt, &out.RelationL3ExtRsL3DomAtt
		*out = new(string)
		**out = **in
	}
	if in.RelationL3ExtRsOutToBdPublicSubnetHolder != nil {
		in, out := &in.RelationL3ExtRsOutToBdPublicSubnetHolder, &out.RelationL3ExtRsOutToBdPublicSubnetHolder
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TargetDscp != nil {
		in, out := &in.TargetDscp, &out.TargetDscp
		*out = new(string)
		**out = **in
	}
	if in.TenantDn != nil {
		in, out := &in.TenantDn, &out.TenantDn
		*out = new(string)
		**out = **in
	}
	if in.TenantDnRef != nil {
		in, out := &in.TenantDnRef, &out.TenantDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.TenantDnSelector != nil {
		in, out := &in.TenantDnSelector, &out.TenantDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3OutsideParameters.
func (in *L3OutsideParameters) DeepCopy() *L3OutsideParameters {
	if in == nil {
		return nil
	}
	out := new(L3OutsideParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3OutsideSpec) DeepCopyInto(out *L3OutsideSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3OutsideSpec.
func (in *L3OutsideSpec) DeepCopy() *L3OutsideSpec {
	if in == nil {
		return nil
	}
	out := new(L3OutsideSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3OutsideStatus) DeepCopyInto(out *L3OutsideStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3OutsideStatus.
func (in *L3OutsideStatus) DeepCopy() *L3OutsideStatus {
	if in == nil {
		return nil
	}
	out := new(L3OutsideStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationFvRsBdToNetflowMonitorPolObservation) DeepCopyInto(out *RelationFvRsBdToNetflowMonitorPolObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationFvRsBdToNetflowMonitorPolObservation.
func (in *RelationFvRsBdToNetflowMonitorPolObservation) DeepCopy() *RelationFvRsBdToNetflowMonitorPolObservation {
	if in == nil {
		return nil
	}
	out := new(RelationFvRsBdToNetflowMonitorPolObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationFvRsBdToNetflowMonitorPolParameters) DeepCopyInto(out *RelationFvRsBdToNetflowMonitorPolParameters) {
	*out = *in
	if in.FltType != nil {
		in, out := &in.FltType, &out.FltType
		*out = new(string)
		**out = **in
	}
	if in.TnNetflowMonitorPolName != nil {
		in, out := &in.TnNetflowMonitorPolName, &out.TnNetflowMonitorPolName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationFvRsBdToNetflowMonitorPolParameters.
func (in *RelationFvRsBdToNetflowMonitorPolParameters) DeepCopy() *RelationFvRsBdToNetflowMonitorPolParameters {
	if in == nil {
		return nil
	}
	out := new(RelationFvRsBdToNetflowMonitorPolParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationFvRsCtxToBGPCtxAfPolObservation) DeepCopyInto(out *RelationFvRsCtxToBGPCtxAfPolObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationFvRsCtxToBGPCtxAfPolObservation.
func (in *RelationFvRsCtxToBGPCtxAfPolObservation) DeepCopy() *RelationFvRsCtxToBGPCtxAfPolObservation {
	if in == nil {
		return nil
	}
	out := new(RelationFvRsCtxToBGPCtxAfPolObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationFvRsCtxToBGPCtxAfPolParameters) DeepCopyInto(out *RelationFvRsCtxToBGPCtxAfPolParameters) {
	*out = *in
	if in.Af != nil {
		in, out := &in.Af, &out.Af
		*out = new(string)
		**out = **in
	}
	if in.TnBGPCtxAfPolName != nil {
		in, out := &in.TnBGPCtxAfPolName, &out.TnBGPCtxAfPolName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationFvRsCtxToBGPCtxAfPolParameters.
func (in *RelationFvRsCtxToBGPCtxAfPolParameters) DeepCopy() *RelationFvRsCtxToBGPCtxAfPolParameters {
	if in == nil {
		return nil
	}
	out := new(RelationFvRsCtxToBGPCtxAfPolParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationFvRsCtxToEigrpCtxAfPolObservation) DeepCopyInto(out *RelationFvRsCtxToEigrpCtxAfPolObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationFvRsCtxToEigrpCtxAfPolObservation.
func (in *RelationFvRsCtxToEigrpCtxAfPolObservation) DeepCopy() *RelationFvRsCtxToEigrpCtxAfPolObservation {
	if in == nil {
		return nil
	}
	out := new(RelationFvRsCtxToEigrpCtxAfPolObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationFvRsCtxToEigrpCtxAfPolParameters) DeepCopyInto(out *RelationFvRsCtxToEigrpCtxAfPolParameters) {
	*out = *in
	if in.Af != nil {
		in, out := &in.Af, &out.Af
		*out = new(string)
		**out = **in
	}
	if in.TnEigrpCtxAfPolName != nil {
		in, out := &in.TnEigrpCtxAfPolName, &out.TnEigrpCtxAfPolName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationFvRsCtxToEigrpCtxAfPolParameters.
func (in *RelationFvRsCtxToEigrpCtxAfPolParameters) DeepCopy() *RelationFvRsCtxToEigrpCtxAfPolParameters {
	if in == nil {
		return nil
	}
	out := new(RelationFvRsCtxToEigrpCtxAfPolParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationFvRsCtxToOspfCtxPolObservation) DeepCopyInto(out *RelationFvRsCtxToOspfCtxPolObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationFvRsCtxToOspfCtxPolObservation.
func (in *RelationFvRsCtxToOspfCtxPolObservation) DeepCopy() *RelationFvRsCtxToOspfCtxPolObservation {
	if in == nil {
		return nil
	}
	out := new(RelationFvRsCtxToOspfCtxPolObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationFvRsCtxToOspfCtxPolParameters) DeepCopyInto(out *RelationFvRsCtxToOspfCtxPolParameters) {
	*out = *in
	if in.Af != nil {
		in, out := &in.Af, &out.Af
		*out = new(string)
		**out = **in
	}
	if in.TnOspfCtxPolName != nil {
		in, out := &in.TnOspfCtxPolName, &out.TnOspfCtxPolName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationFvRsCtxToOspfCtxPolParameters.
func (in *RelationFvRsCtxToOspfCtxPolParameters) DeepCopy() *RelationFvRsCtxToOspfCtxPolParameters {
	if in == nil {
		return nil
	}
	out := new(RelationFvRsCtxToOspfCtxPolParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationL3ExtRsDampeningPolObservation) DeepCopyInto(out *RelationL3ExtRsDampeningPolObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationL3ExtRsDampeningPolObservation.
func (in *RelationL3ExtRsDampeningPolObservation) DeepCopy() *RelationL3ExtRsDampeningPolObservation {
	if in == nil {
		return nil
	}
	out := new(RelationL3ExtRsDampeningPolObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationL3ExtRsDampeningPolParameters) DeepCopyInto(out *RelationL3ExtRsDampeningPolParameters) {
	*out = *in
	if in.Af != nil {
		in, out := &in.Af, &out.Af
		*out = new(string)
		**out = **in
	}
	if in.TnRtctrlProfileName != nil {
		in, out := &in.TnRtctrlProfileName, &out.TnRtctrlProfileName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationL3ExtRsDampeningPolParameters.
func (in *RelationL3ExtRsDampeningPolParameters) DeepCopy() *RelationL3ExtRsDampeningPolParameters {
	if in == nil {
		return nil
	}
	out := new(RelationL3ExtRsDampeningPolParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationL3ExtRsInstPToProfileObservation) DeepCopyInto(out *RelationL3ExtRsInstPToProfileObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationL3ExtRsInstPToProfileObservation.
func (in *RelationL3ExtRsInstPToProfileObservation) DeepCopy() *RelationL3ExtRsInstPToProfileObservation {
	if in == nil {
		return nil
	}
	out := new(RelationL3ExtRsInstPToProfileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationL3ExtRsInstPToProfileParameters) DeepCopyInto(out *RelationL3ExtRsInstPToProfileParameters) {
	*out = *in
	if in.Direction != nil {
		in, out := &in.Direction, &out.Direction
		*out = new(string)
		**out = **in
	}
	if in.TnRtctrlProfileName != nil {
		in, out := &in.TnRtctrlProfileName, &out.TnRtctrlProfileName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationL3ExtRsInstPToProfileParameters.
func (in *RelationL3ExtRsInstPToProfileParameters) DeepCopy() *RelationL3ExtRsInstPToProfileParameters {
	if in == nil {
		return nil
	}
	out := new(RelationL3ExtRsInstPToProfileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationL3ExtRsLIfPToNetflowMonitorPolObservation) DeepCopyInto(out *RelationL3ExtRsLIfPToNetflowMonitorPolObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationL3ExtRsLIfPToNetflowMonitorPolObservation.
func (in *RelationL3ExtRsLIfPToNetflowMonitorPolObservation) DeepCopy() *RelationL3ExtRsLIfPToNetflowMonitorPolObservation {
	if in == nil {
		return nil
	}
	out := new(RelationL3ExtRsLIfPToNetflowMonitorPolObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationL3ExtRsLIfPToNetflowMonitorPolParameters) DeepCopyInto(out *RelationL3ExtRsLIfPToNetflowMonitorPolParameters) {
	*out = *in
	if in.FltType != nil {
		in, out := &in.FltType, &out.FltType
		*out = new(string)
		**out = **in
	}
	if in.TnNetflowMonitorPolName != nil {
		in, out := &in.TnNetflowMonitorPolName, &out.TnNetflowMonitorPolName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationL3ExtRsLIfPToNetflowMonitorPolParameters.
func (in *RelationL3ExtRsLIfPToNetflowMonitorPolParameters) DeepCopy() *RelationL3ExtRsLIfPToNetflowMonitorPolParameters {
	if in == nil {
		return nil
	}
	out := new(RelationL3ExtRsLIfPToNetflowMonitorPolParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationL3ExtRsSubnetToProfileObservation) DeepCopyInto(out *RelationL3ExtRsSubnetToProfileObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationL3ExtRsSubnetToProfileObservation.
func (in *RelationL3ExtRsSubnetToProfileObservation) DeepCopy() *RelationL3ExtRsSubnetToProfileObservation {
	if in == nil {
		return nil
	}
	out := new(RelationL3ExtRsSubnetToProfileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationL3ExtRsSubnetToProfileParameters) DeepCopyInto(out *RelationL3ExtRsSubnetToProfileParameters) {
	*out = *in
	if in.Direction != nil {
		in, out := &in.Direction, &out.Direction
		*out = new(string)
		**out = **in
	}
	if in.TnRtctrlProfileDn != nil {
		in, out := &in.TnRtctrlProfileDn, &out.TnRtctrlProfileDn
		*out = new(string)
		**out = **in
	}
	if in.TnRtctrlProfileName != nil {
		in, out := &in.TnRtctrlProfileName, &out.TnRtctrlProfileName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationL3ExtRsSubnetToProfileParameters.
func (in *RelationL3ExtRsSubnetToProfileParameters) DeepCopy() *RelationL3ExtRsSubnetToProfileParameters {
	if in == nil {
		return nil
	}
	out := new(RelationL3ExtRsSubnetToProfileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Vrf) DeepCopyInto(out *Vrf) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Vrf.
func (in *Vrf) DeepCopy() *Vrf {
	if in == nil {
		return nil
	}
	out := new(Vrf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Vrf) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VrfList) DeepCopyInto(out *VrfList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Vrf, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VrfList.
func (in *VrfList) DeepCopy() *VrfList {
	if in == nil {
		return nil
	}
	out := new(VrfList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VrfList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VrfObservation) DeepCopyInto(out *VrfObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VrfObservation.
func (in *VrfObservation) DeepCopy() *VrfObservation {
	if in == nil {
		return nil
	}
	out := new(VrfObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VrfParameters) DeepCopyInto(out *VrfParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.BdEnforcedEnable != nil {
		in, out := &in.BdEnforcedEnable, &out.BdEnforcedEnable
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.IPDataPlaneLearning != nil {
		in, out := &in.IPDataPlaneLearning, &out.IPDataPlaneLearning
		*out = new(string)
		**out = **in
	}
	if in.KnwMcastAct != nil {
		in, out := &in.KnwMcastAct, &out.KnwMcastAct
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
	if in.PcEnfDir != nil {
		in, out := &in.PcEnfDir, &out.PcEnfDir
		*out = new(string)
		**out = **in
	}
	if in.PcEnfPref != nil {
		in, out := &in.PcEnfPref, &out.PcEnfPref
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsBGPCtxPol != nil {
		in, out := &in.RelationFvRsBGPCtxPol, &out.RelationFvRsBGPCtxPol
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsCtxMcastTo != nil {
		in, out := &in.RelationFvRsCtxMcastTo, &out.RelationFvRsCtxMcastTo
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsCtxMonPol != nil {
		in, out := &in.RelationFvRsCtxMonPol, &out.RelationFvRsCtxMonPol
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsCtxToBGPCtxAfPol != nil {
		in, out := &in.RelationFvRsCtxToBGPCtxAfPol, &out.RelationFvRsCtxToBGPCtxAfPol
		*out = make([]RelationFvRsCtxToBGPCtxAfPolParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RelationFvRsCtxToEigrpCtxAfPol != nil {
		in, out := &in.RelationFvRsCtxToEigrpCtxAfPol, &out.RelationFvRsCtxToEigrpCtxAfPol
		*out = make([]RelationFvRsCtxToEigrpCtxAfPolParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RelationFvRsCtxToEpRet != nil {
		in, out := &in.RelationFvRsCtxToEpRet, &out.RelationFvRsCtxToEpRet
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsCtxToExtRouteTagPol != nil {
		in, out := &in.RelationFvRsCtxToExtRouteTagPol, &out.RelationFvRsCtxToExtRouteTagPol
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsCtxToOspfCtxPol != nil {
		in, out := &in.RelationFvRsCtxToOspfCtxPol, &out.RelationFvRsCtxToOspfCtxPol
		*out = make([]RelationFvRsCtxToOspfCtxPolParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RelationFvRsOspfCtxPol != nil {
		in, out := &in.RelationFvRsOspfCtxPol, &out.RelationFvRsOspfCtxPol
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsVrfValidationPol != nil {
		in, out := &in.RelationFvRsVrfValidationPol, &out.RelationFvRsVrfValidationPol
		*out = new(string)
		**out = **in
	}
	if in.TenantDn != nil {
		in, out := &in.TenantDn, &out.TenantDn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VrfParameters.
func (in *VrfParameters) DeepCopy() *VrfParameters {
	if in == nil {
		return nil
	}
	out := new(VrfParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VrfSpec) DeepCopyInto(out *VrfSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VrfSpec.
func (in *VrfSpec) DeepCopy() *VrfSpec {
	if in == nil {
		return nil
	}
	out := new(VrfSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VrfStatus) DeepCopyInto(out *VrfStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VrfStatus.
func (in *VrfStatus) DeepCopy() *VrfStatus {
	if in == nil {
		return nil
	}
	out := new(VrfStatus)
	in.DeepCopyInto(out)
	return out
}
