//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationProfile) DeepCopyInto(out *ApplicationProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationProfile.
func (in *ApplicationProfile) DeepCopy() *ApplicationProfile {
	if in == nil {
		return nil
	}
	out := new(ApplicationProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationProfileList) DeepCopyInto(out *ApplicationProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApplicationProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationProfileList.
func (in *ApplicationProfileList) DeepCopy() *ApplicationProfileList {
	if in == nil {
		return nil
	}
	out := new(ApplicationProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationProfileObservation) DeepCopyInto(out *ApplicationProfileObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationProfileObservation.
func (in *ApplicationProfileObservation) DeepCopy() *ApplicationProfileObservation {
	if in == nil {
		return nil
	}
	out := new(ApplicationProfileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationProfileParameters) DeepCopyInto(out *ApplicationProfileParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
	if in.Prio != nil {
		in, out := &in.Prio, &out.Prio
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsApMonPol != nil {
		in, out := &in.RelationFvRsApMonPol, &out.RelationFvRsApMonPol
		*out = new(string)
		**out = **in
	}
	if in.TenantDn != nil {
		in, out := &in.TenantDn, &out.TenantDn
		*out = new(string)
		**out = **in
	}
	if in.TenantDnRef != nil {
		in, out := &in.TenantDnRef, &out.TenantDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.TenantDnSelector != nil {
		in, out := &in.TenantDnSelector, &out.TenantDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationProfileParameters.
func (in *ApplicationProfileParameters) DeepCopy() *ApplicationProfileParameters {
	if in == nil {
		return nil
	}
	out := new(ApplicationProfileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationProfileSpec) DeepCopyInto(out *ApplicationProfileSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationProfileSpec.
func (in *ApplicationProfileSpec) DeepCopy() *ApplicationProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationProfileStatus) DeepCopyInto(out *ApplicationProfileStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationProfileStatus.
func (in *ApplicationProfileStatus) DeepCopy() *ApplicationProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Epg) DeepCopyInto(out *Epg) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Epg.
func (in *Epg) DeepCopy() *Epg {
	if in == nil {
		return nil
	}
	out := new(Epg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Epg) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EpgList) DeepCopyInto(out *EpgList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Epg, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EpgList.
func (in *EpgList) DeepCopy() *EpgList {
	if in == nil {
		return nil
	}
	out := new(EpgList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EpgList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EpgObservation) DeepCopyInto(out *EpgObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EpgObservation.
func (in *EpgObservation) DeepCopy() *EpgObservation {
	if in == nil {
		return nil
	}
	out := new(EpgObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EpgParameters) DeepCopyInto(out *EpgParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.ApplicationProfileDn != nil {
		in, out := &in.ApplicationProfileDn, &out.ApplicationProfileDn
		*out = new(string)
		**out = **in
	}
	if in.ApplicationProfileDnRef != nil {
		in, out := &in.ApplicationProfileDnRef, &out.ApplicationProfileDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.ApplicationProfileDnSelector != nil {
		in, out := &in.ApplicationProfileDnSelector, &out.ApplicationProfileDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ExceptionTag != nil {
		in, out := &in.ExceptionTag, &out.ExceptionTag
		*out = new(string)
		**out = **in
	}
	if in.FloodOnEncap != nil {
		in, out := &in.FloodOnEncap, &out.FloodOnEncap
		*out = new(string)
		**out = **in
	}
	if in.FwdCtrl != nil {
		in, out := &in.FwdCtrl, &out.FwdCtrl
		*out = new(string)
		**out = **in
	}
	if in.HasMcastSource != nil {
		in, out := &in.HasMcastSource, &out.HasMcastSource
		*out = new(string)
		**out = **in
	}
	if in.IsAttrBasedEpg != nil {
		in, out := &in.IsAttrBasedEpg, &out.IsAttrBasedEpg
		*out = new(string)
		**out = **in
	}
	if in.MatchT != nil {
		in, out := &in.MatchT, &out.MatchT
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
	if in.PcEnfPref != nil {
		in, out := &in.PcEnfPref, &out.PcEnfPref
		*out = new(string)
		**out = **in
	}
	if in.PrefGrMemb != nil {
		in, out := &in.PrefGrMemb, &out.PrefGrMemb
		*out = new(string)
		**out = **in
	}
	if in.Prio != nil {
		in, out := &in.Prio, &out.Prio
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsAepgMonPol != nil {
		in, out := &in.RelationFvRsAepgMonPol, &out.RelationFvRsAepgMonPol
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsBd != nil {
		in, out := &in.RelationFvRsBd, &out.RelationFvRsBd
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsCons != nil {
		in, out := &in.RelationFvRsCons, &out.RelationFvRsCons
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsConsIf != nil {
		in, out := &in.RelationFvRsConsIf, &out.RelationFvRsConsIf
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsCustQosPol != nil {
		in, out := &in.RelationFvRsCustQosPol, &out.RelationFvRsCustQosPol
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsDppPol != nil {
		in, out := &in.RelationFvRsDppPol, &out.RelationFvRsDppPol
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsFcPathAtt != nil {
		in, out := &in.RelationFvRsFcPathAtt, &out.RelationFvRsFcPathAtt
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsIntraEpg != nil {
		in, out := &in.RelationFvRsIntraEpg, &out.RelationFvRsIntraEpg
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsNodeAtt != nil {
		in, out := &in.RelationFvRsNodeAtt, &out.RelationFvRsNodeAtt
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsPathAtt != nil {
		in, out := &in.RelationFvRsPathAtt, &out.RelationFvRsPathAtt
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsProtBy != nil {
		in, out := &in.RelationFvRsProtBy, &out.RelationFvRsProtBy
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsProv != nil {
		in, out := &in.RelationFvRsProv, &out.RelationFvRsProv
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsProvDef != nil {
		in, out := &in.RelationFvRsProvDef, &out.RelationFvRsProvDef
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsSecInherited != nil {
		in, out := &in.RelationFvRsSecInherited, &out.RelationFvRsSecInherited
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsTrustCtrl != nil {
		in, out := &in.RelationFvRsTrustCtrl, &out.RelationFvRsTrustCtrl
		*out = new(string)
		**out = **in
	}
	if in.Shutdown != nil {
		in, out := &in.Shutdown, &out.Shutdown
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EpgParameters.
func (in *EpgParameters) DeepCopy() *EpgParameters {
	if in == nil {
		return nil
	}
	out := new(EpgParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EpgSpec) DeepCopyInto(out *EpgSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EpgSpec.
func (in *EpgSpec) DeepCopy() *EpgSpec {
	if in == nil {
		return nil
	}
	out := new(EpgSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EpgStatus) DeepCopyInto(out *EpgStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EpgStatus.
func (in *EpgStatus) DeepCopy() *EpgStatus {
	if in == nil {
		return nil
	}
	out := new(EpgStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Esg) DeepCopyInto(out *Esg) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Esg.
func (in *Esg) DeepCopy() *Esg {
	if in == nil {
		return nil
	}
	out := new(Esg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Esg) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgEpgSelector) DeepCopyInto(out *EsgEpgSelector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgEpgSelector.
func (in *EsgEpgSelector) DeepCopy() *EsgEpgSelector {
	if in == nil {
		return nil
	}
	out := new(EsgEpgSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EsgEpgSelector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgEpgSelectorList) DeepCopyInto(out *EsgEpgSelectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EsgEpgSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgEpgSelectorList.
func (in *EsgEpgSelectorList) DeepCopy() *EsgEpgSelectorList {
	if in == nil {
		return nil
	}
	out := new(EsgEpgSelectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EsgEpgSelectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgEpgSelectorObservation) DeepCopyInto(out *EsgEpgSelectorObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgEpgSelectorObservation.
func (in *EsgEpgSelectorObservation) DeepCopy() *EsgEpgSelectorObservation {
	if in == nil {
		return nil
	}
	out := new(EsgEpgSelectorObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgEpgSelectorParameters) DeepCopyInto(out *EsgEpgSelectorParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EndpointSecurityGroupDn != nil {
		in, out := &in.EndpointSecurityGroupDn, &out.EndpointSecurityGroupDn
		*out = new(string)
		**out = **in
	}
	if in.EndpointSecurityGroupDnRef != nil {
		in, out := &in.EndpointSecurityGroupDnRef, &out.EndpointSecurityGroupDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.EndpointSecurityGroupDnSelector != nil {
		in, out := &in.EndpointSecurityGroupDnSelector, &out.EndpointSecurityGroupDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.MatchEpgDn != nil {
		in, out := &in.MatchEpgDn, &out.MatchEpgDn
		*out = new(string)
		**out = **in
	}
	if in.MatchEpgDnRef != nil {
		in, out := &in.MatchEpgDnRef, &out.MatchEpgDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.MatchEpgDnSelector != nil {
		in, out := &in.MatchEpgDnSelector, &out.MatchEpgDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgEpgSelectorParameters.
func (in *EsgEpgSelectorParameters) DeepCopy() *EsgEpgSelectorParameters {
	if in == nil {
		return nil
	}
	out := new(EsgEpgSelectorParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgEpgSelectorSpec) DeepCopyInto(out *EsgEpgSelectorSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgEpgSelectorSpec.
func (in *EsgEpgSelectorSpec) DeepCopy() *EsgEpgSelectorSpec {
	if in == nil {
		return nil
	}
	out := new(EsgEpgSelectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgEpgSelectorStatus) DeepCopyInto(out *EsgEpgSelectorStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgEpgSelectorStatus.
func (in *EsgEpgSelectorStatus) DeepCopy() *EsgEpgSelectorStatus {
	if in == nil {
		return nil
	}
	out := new(EsgEpgSelectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgList) DeepCopyInto(out *EsgList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Esg, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgList.
func (in *EsgList) DeepCopy() *EsgList {
	if in == nil {
		return nil
	}
	out := new(EsgList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EsgList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgObservation) DeepCopyInto(out *EsgObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgObservation.
func (in *EsgObservation) DeepCopy() *EsgObservation {
	if in == nil {
		return nil
	}
	out := new(EsgObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgParameters) DeepCopyInto(out *EsgParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.ApplicationProfileDn != nil {
		in, out := &in.ApplicationProfileDn, &out.ApplicationProfileDn
		*out = new(string)
		**out = **in
	}
	if in.ApplicationProfileDnRef != nil {
		in, out := &in.ApplicationProfileDnRef, &out.ApplicationProfileDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.ApplicationProfileDnSelector != nil {
		in, out := &in.ApplicationProfileDnSelector, &out.ApplicationProfileDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.MatchT != nil {
		in, out := &in.MatchT, &out.MatchT
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
	if in.PcEnfPref != nil {
		in, out := &in.PcEnfPref, &out.PcEnfPref
		*out = new(string)
		**out = **in
	}
	if in.PrefGrMemb != nil {
		in, out := &in.PrefGrMemb, &out.PrefGrMemb
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsCons != nil {
		in, out := &in.RelationFvRsCons, &out.RelationFvRsCons
		*out = make([]RelationFvRsConsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RelationFvRsConsIf != nil {
		in, out := &in.RelationFvRsConsIf, &out.RelationFvRsConsIf
		*out = make([]RelationFvRsConsIfParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RelationFvRsCustQosPol != nil {
		in, out := &in.RelationFvRsCustQosPol, &out.RelationFvRsCustQosPol
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsIntraEpg != nil {
		in, out := &in.RelationFvRsIntraEpg, &out.RelationFvRsIntraEpg
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsProtBy != nil {
		in, out := &in.RelationFvRsProtBy, &out.RelationFvRsProtBy
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RelationFvRsProv != nil {
		in, out := &in.RelationFvRsProv, &out.RelationFvRsProv
		*out = make([]RelationFvRsProvParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RelationFvRsScope != nil {
		in, out := &in.RelationFvRsScope, &out.RelationFvRsScope
		*out = new(string)
		**out = **in
	}
	if in.RelationFvRsScopeRef != nil {
		in, out := &in.RelationFvRsScopeRef, &out.RelationFvRsScopeRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.RelationFvRsScopeSelector != nil {
		in, out := &in.RelationFvRsScopeSelector, &out.RelationFvRsScopeSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.RelationFvRsSecInherited != nil {
		in, out := &in.RelationFvRsSecInherited, &out.RelationFvRsSecInherited
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgParameters.
func (in *EsgParameters) DeepCopy() *EsgParameters {
	if in == nil {
		return nil
	}
	out := new(EsgParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgSelector) DeepCopyInto(out *EsgSelector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgSelector.
func (in *EsgSelector) DeepCopy() *EsgSelector {
	if in == nil {
		return nil
	}
	out := new(EsgSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EsgSelector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgSelectorList) DeepCopyInto(out *EsgSelectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EsgSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgSelectorList.
func (in *EsgSelectorList) DeepCopy() *EsgSelectorList {
	if in == nil {
		return nil
	}
	out := new(EsgSelectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EsgSelectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgSelectorObservation) DeepCopyInto(out *EsgSelectorObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgSelectorObservation.
func (in *EsgSelectorObservation) DeepCopy() *EsgSelectorObservation {
	if in == nil {
		return nil
	}
	out := new(EsgSelectorObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgSelectorParameters) DeepCopyInto(out *EsgSelectorParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EndpointSecurityGroupDn != nil {
		in, out := &in.EndpointSecurityGroupDn, &out.EndpointSecurityGroupDn
		*out = new(string)
		**out = **in
	}
	if in.EndpointSecurityGroupDnRef != nil {
		in, out := &in.EndpointSecurityGroupDnRef, &out.EndpointSecurityGroupDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.EndpointSecurityGroupDnSelector != nil {
		in, out := &in.EndpointSecurityGroupDnSelector, &out.EndpointSecurityGroupDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.MatchExpression != nil {
		in, out := &in.MatchExpression, &out.MatchExpression
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgSelectorParameters.
func (in *EsgSelectorParameters) DeepCopy() *EsgSelectorParameters {
	if in == nil {
		return nil
	}
	out := new(EsgSelectorParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgSelectorSpec) DeepCopyInto(out *EsgSelectorSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgSelectorSpec.
func (in *EsgSelectorSpec) DeepCopy() *EsgSelectorSpec {
	if in == nil {
		return nil
	}
	out := new(EsgSelectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgSelectorStatus) DeepCopyInto(out *EsgSelectorStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgSelectorStatus.
func (in *EsgSelectorStatus) DeepCopy() *EsgSelectorStatus {
	if in == nil {
		return nil
	}
	out := new(EsgSelectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgSpec) DeepCopyInto(out *EsgSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgSpec.
func (in *EsgSpec) DeepCopy() *EsgSpec {
	if in == nil {
		return nil
	}
	out := new(EsgSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgStatus) DeepCopyInto(out *EsgStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgStatus.
func (in *EsgStatus) DeepCopy() *EsgStatus {
	if in == nil {
		return nil
	}
	out := new(EsgStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgTagSelector) DeepCopyInto(out *EsgTagSelector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgTagSelector.
func (in *EsgTagSelector) DeepCopy() *EsgTagSelector {
	if in == nil {
		return nil
	}
	out := new(EsgTagSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EsgTagSelector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgTagSelectorList) DeepCopyInto(out *EsgTagSelectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EsgTagSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgTagSelectorList.
func (in *EsgTagSelectorList) DeepCopy() *EsgTagSelectorList {
	if in == nil {
		return nil
	}
	out := new(EsgTagSelectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EsgTagSelectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgTagSelectorObservation) DeepCopyInto(out *EsgTagSelectorObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgTagSelectorObservation.
func (in *EsgTagSelectorObservation) DeepCopy() *EsgTagSelectorObservation {
	if in == nil {
		return nil
	}
	out := new(EsgTagSelectorObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgTagSelectorParameters) DeepCopyInto(out *EsgTagSelectorParameters) {
	*out = *in
	if in.Annotation != nil {
		in, out := &in.Annotation, &out.Annotation
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EndpointSecurityGroupDn != nil {
		in, out := &in.EndpointSecurityGroupDn, &out.EndpointSecurityGroupDn
		*out = new(string)
		**out = **in
	}
	if in.EndpointSecurityGroupDnRef != nil {
		in, out := &in.EndpointSecurityGroupDnRef, &out.EndpointSecurityGroupDnRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.EndpointSecurityGroupDnSelector != nil {
		in, out := &in.EndpointSecurityGroupDnSelector, &out.EndpointSecurityGroupDnSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.MatchKey != nil {
		in, out := &in.MatchKey, &out.MatchKey
		*out = new(string)
		**out = **in
	}
	if in.MatchValue != nil {
		in, out := &in.MatchValue, &out.MatchValue
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameAlias != nil {
		in, out := &in.NameAlias, &out.NameAlias
		*out = new(string)
		**out = **in
	}
	if in.ValueOperator != nil {
		in, out := &in.ValueOperator, &out.ValueOperator
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgTagSelectorParameters.
func (in *EsgTagSelectorParameters) DeepCopy() *EsgTagSelectorParameters {
	if in == nil {
		return nil
	}
	out := new(EsgTagSelectorParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgTagSelectorSpec) DeepCopyInto(out *EsgTagSelectorSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgTagSelectorSpec.
func (in *EsgTagSelectorSpec) DeepCopy() *EsgTagSelectorSpec {
	if in == nil {
		return nil
	}
	out := new(EsgTagSelectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsgTagSelectorStatus) DeepCopyInto(out *EsgTagSelectorStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsgTagSelectorStatus.
func (in *EsgTagSelectorStatus) DeepCopy() *EsgTagSelectorStatus {
	if in == nil {
		return nil
	}
	out := new(EsgTagSelectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationFvRsConsIfObservation) DeepCopyInto(out *RelationFvRsConsIfObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationFvRsConsIfObservation.
func (in *RelationFvRsConsIfObservation) DeepCopy() *RelationFvRsConsIfObservation {
	if in == nil {
		return nil
	}
	out := new(RelationFvRsConsIfObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationFvRsConsIfParameters) DeepCopyInto(out *RelationFvRsConsIfParameters) {
	*out = *in
	if in.Prio != nil {
		in, out := &in.Prio, &out.Prio
		*out = new(string)
		**out = **in
	}
	if in.TargetDn != nil {
		in, out := &in.TargetDn, &out.TargetDn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationFvRsConsIfParameters.
func (in *RelationFvRsConsIfParameters) DeepCopy() *RelationFvRsConsIfParameters {
	if in == nil {
		return nil
	}
	out := new(RelationFvRsConsIfParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationFvRsConsObservation) DeepCopyInto(out *RelationFvRsConsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationFvRsConsObservation.
func (in *RelationFvRsConsObservation) DeepCopy() *RelationFvRsConsObservation {
	if in == nil {
		return nil
	}
	out := new(RelationFvRsConsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationFvRsConsParameters) DeepCopyInto(out *RelationFvRsConsParameters) {
	*out = *in
	if in.Prio != nil {
		in, out := &in.Prio, &out.Prio
		*out = new(string)
		**out = **in
	}
	if in.TargetDn != nil {
		in, out := &in.TargetDn, &out.TargetDn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationFvRsConsParameters.
func (in *RelationFvRsConsParameters) DeepCopy() *RelationFvRsConsParameters {
	if in == nil {
		return nil
	}
	out := new(RelationFvRsConsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationFvRsProvObservation) DeepCopyInto(out *RelationFvRsProvObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationFvRsProvObservation.
func (in *RelationFvRsProvObservation) DeepCopy() *RelationFvRsProvObservation {
	if in == nil {
		return nil
	}
	out := new(RelationFvRsProvObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationFvRsProvParameters) DeepCopyInto(out *RelationFvRsProvParameters) {
	*out = *in
	if in.MatchT != nil {
		in, out := &in.MatchT, &out.MatchT
		*out = new(string)
		**out = **in
	}
	if in.Prio != nil {
		in, out := &in.Prio, &out.Prio
		*out = new(string)
		**out = **in
	}
	if in.TargetDn != nil {
		in, out := &in.TargetDn, &out.TargetDn
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationFvRsProvParameters.
func (in *RelationFvRsProvParameters) DeepCopy() *RelationFvRsProvParameters {
	if in == nil {
		return nil
	}
	out := new(RelationFvRsProvParameters)
	in.DeepCopyInto(out)
	return out
}
